### ISSUE TITLE
[QUESTION] What purpose does the `validate_sdrfs.sh` script have in this repo?

### ISSUE THREAD

**Issue by fabianegli** [bigbio/sdrf-pipelines#110]
I couldn't find it mentioned/referenced anywhere in this repository. That's why I wonder if it serves any purpose at all.

**Comment by ypriverol** [comment]
This can be removed. The original purpose was to validate with that script exiting datasets already annotated in sdrf. In your first PR 😜  feel free to remove it.

**Comment by fabianegli** [comment]
I saw that the integration test was running on just one example of a conversion. If the different files in the script have different content, i.e. different columns/values/use cases from various experimental setups and modifications, it might be beneficial to collect them and run the integration tests on as many different SDRF files as we have use cases.

The repo also lacks any integration tests for runs that are expected to fail if I am not mistaken.

**Comment by fabianegli** [comment]
@ypriverol Do you have a set of SDRF files for experiments of all different kinds of expected flavors? 

If not we should systematically generate SDRF example files with all the different labelling techniques, fractionations, biological and technical replicates, file names (spaces/weird characters, if allowable) to have test cases for at least the most common experimental setups. Based on those we can then generate examples of SDRF files that do not comply with the standard, but should be readable nonetheless and some that are wrong in various ways we expect users to mess up writing SDRF files with common tools or even by hand.

**Comment by fabianegli** [comment]
Moving the integration test file question to a new issue...

**Comment by fabianegli** [comment]
reopening, because the file is not yet deleted. The question about SDRF files for integration testing moved to #112

**Comment by fabianegli** [comment]
Closed by #116
