### ISSUE TITLE
[MAINT] rename master branch to main

### ISSUE THREAD

**Issue by fabianegli** [bigbio/sdrf-pipelines#117]
It would be extremely nice to have the central branch of this repository renamed from master to main. This comes with some issues, but should be considered a a plus when it comes to inclusiveness. See https://github.com/github/renaming for reference.

**Comment by ypriverol** [comment]
Hi @fabianegli we actually always use in our projects master, and we don't see any benefit on moving from one name to another. But problaby others can vote @jpfeuffer @levitsky. If we decide to rename the branch it needs to be one of the last thing to do because forks, releases, CI/CD everything in based on `master`.

**Comment by fabianegli** [comment]
This change is not meant to be benefitting the current developers/maintainers. I know it is additional work with negligible immediate return but that is not the point. It makes sure people who may find `master` offensive to not be constantly reminded of that. We go with the time when it comes to technology, we should do the same with social issues.

As for the additional forks, there is only one in the network that actually has some work done and that's the one from `elixir-proteomics-community`. I am sure that can be coordinated. 

The `master` branch is now protected, so no one can push to it anyway and PRs are done across branches. Renaming will not have deteriorating impacts on MRs, as far as I can tell.

Workload wise, I am convinced the longer the project lives the more hardcoded "master" strings will be in the CI and in other places. Especially since we are now planing to add additional CI Actions.

Lastly, there is an immediate benefit: main is only 4 characters to type, master is 6, so main is a it is a 33.33% improvement over master.

**Comment by ypriverol** [comment]
Done. !!!
