### ISSUE TITLE
[SECURITY] Move from xml to defusedxml for XML parsing

### ISSUE THREAD

**Issue by fabianegli** [bigbio/sdrf-pipelines#119]
XML is not save to parse in its original specification. See the official official Python builtin [`xml` documentation](https://docs.python.org/3/library/xml.html) which promotes the use of the [`defusedxml`](https://pypi.org/project/defusedxml/) package. [`Pyre` in the CI of this repo](https://lift.sonatype.com/results/github.com/bigbio/sdrf-pipelines/01FZWXVT003KTYQFM3ZVYES5HC) is complaining about it, too.

The reason why this is important is because we can not know whether or not the XML files a user parses is benign or not. We should protect our users from known security vulnerabilities.

**Comment by ypriverol** [comment]
#148 this will be tackling the issue.
