### ISSUE TITLE
[ENH] Have a "--version" parameter to print versions

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/sdrf-pipelines#122]
Important for auto reporting versions of tools used in workflows.

**Comment by ypriverol** [comment]
We have a new student, that will be taking care of this small issues @jpfeuffer.

**Comment by fabianegli** [comment]
Is this currently being worked on?

**Comment by ypriverol** [comment]
I haven't been able to work on this issue. If you have some time, you can go for it.

**Comment by fabianegli** [comment]
@ypriverol  Just made the PR. would be great to get some feedback if the version reporting format suits your needs or if it should be adapted to another format.

**Comment by fabianegli** [comment]
Also the way it is implemented could be changed if there's a reason to. Other options can be found in the single source version link in the PR.
