### ISSUE TITLE
The column technology typecannot be before the assay name -- ERROR

### ISSUE THREAD

**Issue by levitsky** [bigbio/sdrf-pipelines#177]
The validator throws this error, but `technology type` is before `assay name` in the [template](https://github.com/bigbio/proteomics-sample-metadata/blob/master/templates/sdrf-human.sdrf.tsv). Which order is correct?

**Comment by ypriverol** [comment]
@levitsky can you tackle this issue?

**Comment by levitsky** [comment]
I can take a look tomorrow :)
