### ISSUE TITLE
problems with dependency in conda

### ISSUE THREAD

**Issue by ypriverol** [bigbio/sdrf-pipelines#46]
@daichengxin the dependency introduce: pyecharts is stopping the project to be built in conda because this dependency is not in Conda. Can we use another library for this that at least is in conda-forge.

**Comment by ypriverol** [comment]
For now, I will remove the code from the library and we will include it when the changes are incorporate.

**Comment by ypriverol** [comment]
Branch with visualization https://github.com/bigbio/sdrf-pipelines/tree/visualization

**Comment by baimingze** [comment]
I suggest you have a try on Plotly, which can be install from Anaconda, and also can generate interactive graphs.
