### ISSUE TITLE
Order of properties not validated 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/sdrf-pipelines#69]
Can we validate the following rules: 

- [ ] No comment can be before assay name. 
- [ ] No characteristics can be after assay name. 
- [ ] Can you implement the logic of splitting and SDRF by columns, for example, the user can say, `source name` and it will spliit the SDRF into multiple SDRFs where all the rows on each of the SDRF correspond to one specific value. This will help for example to split SDRFs by facor value, samples, instruments etc. The user should be able to pass a prefix for the output files or you can take the SDRF name and then, add the value replacing spaces by `-`, example: PXD000621.sdrf.tsv can be 
    - PXD000621-Sample-1.sdrf.tsv
    - PXD000621-Sample-2.sdrf.tsv
 etc. A prototype here: https://github.com/multiomics/multiomics-configs/blob/master/datasets/python_sdrf_splitter.py
- [ ] We need to implement also a mechanism to merge SDRFs.

**Comment by daichengxin** [comment]
ok. I will be working on it

**Comment by daichengxin** [comment]
Hi Yasset @ypriverol . For split sdrf function, can the users provide multiple attributes for segmentation? More than two

**Comment by ypriverol** [comment]
Yes,  think in the script we allow that.

**Comment by daichengxin** [comment]
Hi Yasset @ypriverol , for merging sdrf files, there are several options: 

1. Merge sdrf directly by line (inverse operation of split sdrf)
2. The intersection of two SDRF column name serves as a connector?
3. Is there any other merger mechanism?

**Comment by ypriverol** [comment]
The merge is complex because the tool, needs for example, to evaluate if one column (e.g. species) has the same value for the two samples, it shouldn't create another column but if the column is for example PTM then it should create two columns,.
