### ISSUE TITLE
OpenMS Exporter recently broke

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/sdrf-pipelines#72]
Hi,

recent commits broke the OpenMS converter. It has to do with making the conditions a semicolon-separated list and only putting the first element to the OpenMS experimental design.
E.g. for PXD0001819 we now get (for the sample table):

```
Sample  MSstats_Condition       MSstats_BioReplicate
1       CT=mixture      1
2       CT=mixture      2
3       CT=mixture      3
4       CT=mixture      4
5       CT=mixture      5
6       CT=mixture      6
7       CT=mixture      7
8       CT=mixture      8
9       CT=mixture      9
```

But we would like to have either the full entry "CT=mixture;QN=500amol...." or maybe even better for readability only the values of this "dictionary" (e.g. something like "mixture UPS1 500amol").
It has quite some high priority since it breaks the whole pipeline so go ahead with what is easiest/quickest for now.
Thanks!

**Comment by timosachsenberg** [comment]
In light that this is rather time sensitive - can we revert the workflow to a state before the labels were introduced. Add tests/CI first and then add label support?

**Comment by daichengxin** [comment]
Thanks to @jpfeuffer for suggesting TOdos, I am changing the code

**Comment by daichengxin** [comment]
Hi @jpfeuffer Sorry for the inconvenience ,I just submitted the fixed code, and there are two comments in it that I cannot understand. 

1. `    # TODO How does this work? In OpenMS there are no such modifications. You can have different "isotope mods"
        #  for light, medium and heavy. E.g. Label:13C(2)15N(2) (K) as light or Dimethyl:2H(2)13C (K) as light`
2. `   # TODO if at all, this only works if the labels for the same file are consecutive in the SDRF and always
        #  in the same order as specified in the initial labels dictionary. Very Dangerous!`
I saw the details in https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/classOpenMS_1_1ExperimentalDesign.html

**Comment by jpfeuffer** [comment]
Hi!

I just had a quick view over the code.
I think those points are not wrong.

1) There has to be an additional modification in the SDRF to specify which SILAC mod it was.
2) This is fine. I thought you were accessing the label names by index not by name. But it might be easier if there are two data structures, one for properties per file and one for properties per "sample" (=file*label).

Thanks for the quick response
