### ISSUE TITLE
maxquant parameter file cannot have fragment and precursor tolerance in different units

### ISSUE THREAD

**Issue by veitveit** [bigbio/sdrf-pipelines#89]
sdrf-parser runs into problems when the tolerances are given in different units (Da and ppm) as MaxQuant needs them to be the same. 

I am not sure about the actual outcome, but when running a sdrf file with fragment tolerance given in Da, the MaxQuant parameter `<searchTolInPpm>True</searchTolInPpm>` is still set to ppm. This means that the tolerance most likely will be wrongly translated.

And there is no warning or alike. 

You might need to convert the units.

**Comment by daichengxin** [comment]
Yes, MaxQuant requires the same unit of precursor and fragment. I will first set a warning before finding the suitable unit conversion. ppm<->Da
